// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FOO int32

const (
	FOO_Unknown FOO = 0
	FOO_X       FOO = 17
)

var FOO_name = map[int32]string{
	0:  "Unknown",
	17: "X",
}

var FOO_value = map[string]int32{
	"Unknown": 0,
	"X":       17,
}

func (x FOO) String() string {
	return proto.EnumName(FOO_name, int32(x))
}

func (FOO) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

type Test struct {
	Label string  `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Type  int32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Reps  []int64 `protobuf:"varint,3,rep,packed,name=reps,proto3" json:"reps,omitempty"`
	// group OptionalGroup = 4 {
	//   string RequiredField = 5;
	// }
	//
	// Types that are valid to be assigned to Union:
	//	*Test_Number
	//	*Test_Name
	Union                isTest_Union `protobuf_oneof:"union"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Test) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

type isTest_Union interface {
	isTest_Union()
}

type Test_Number struct {
	Number int32 `protobuf:"varint,6,opt,name=number,proto3,oneof"`
}

type Test_Name struct {
	Name string `protobuf:"bytes,7,opt,name=name,proto3,oneof"`
}

func (*Test_Number) isTest_Union() {}

func (*Test_Name) isTest_Union() {}

func (m *Test) GetUnion() isTest_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *Test) GetNumber() int32 {
	if x, ok := m.GetUnion().(*Test_Number); ok {
		return x.Number
	}
	return 0
}

func (m *Test) GetName() string {
	if x, ok := m.GetUnion().(*Test_Name); ok {
		return x.Name
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Test) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Test_Number)(nil),
		(*Test_Name)(nil),
	}
}

func init() {
	proto.RegisterEnum("example.FOO", FOO_name, FOO_value)
	proto.RegisterType((*Test)(nil), "example.Test")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x6a, 0xb9,
	0x58, 0x42, 0x52, 0x8b, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0x73, 0x12, 0x93, 0x52, 0x73, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x30, 0x1b, 0x24, 0x56, 0x94, 0x5a, 0x50, 0x2c, 0xc1, 0xac,
	0xc0, 0xac, 0xc1, 0x1c, 0x04, 0x66, 0x0b, 0x49, 0x70, 0xb1, 0xe5, 0x95, 0xe6, 0x26, 0xa5, 0x16,
	0x49, 0xb0, 0x81, 0x54, 0x7a, 0x30, 0x04, 0x41, 0xf9, 0x42, 0x22, 0x5c, 0x2c, 0x79, 0x89, 0xb9,
	0xa9, 0x12, 0xec, 0x20, 0x63, 0x3d, 0x18, 0x82, 0xc0, 0x3c, 0x27, 0x76, 0x2e, 0xd6, 0xd2, 0xbc,
	0xcc, 0xfc, 0x3c, 0x2d, 0x49, 0x2e, 0x66, 0x37, 0x7f, 0x7f, 0x21, 0x6e, 0x2e, 0xf6, 0xd0, 0xbc,
	0xec, 0xbc, 0xfc, 0xf2, 0x3c, 0x01, 0x06, 0x21, 0x56, 0x2e, 0xc6, 0x08, 0x01, 0xc1, 0x24, 0x36,
	0xb0, 0x4b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x3f, 0x2b, 0xf4, 0xba, 0x00, 0x00,
	0x00,
}
